from .colony import *

# base tile class
class Tile:
    def __init__(self, terrain: str, x: int, y: int, colony: Colony | None, gfx: str):
        self.terrain = terrain
        self.x, self.y = x, y
        self.colony = colony
        self.graphic = gfx

# TODO unused, maybe get rid of this
class BaseTile(Tile):
    def __init__(self, x, y, colony):
        super().__init__('TILE_BASE', x, y, colony, 'base')

# all types of tiles generated by the game
class PlainsTile(Tile):
    def __init__(self, x, y, colony):
        super().__init__('TILE_PLAINS', x, y, colony, 'grass')

class ForestTile(Tile):
    def __init__(self, x, y, colony):
        super().__init__('TILE_FOREST', x, y, colony, 'forest')

class MountainTile(Tile):
    def __init__(self, x, y, colony):
        super().__init__('TILE_MOUNTAIN', x, y, colony, 'mountain')

class BeachTile(Tile):
    def __init__(self, x, y, colony):
        super().__init__('TILE_BEACH', x, y, colony, 'sand')

class OceanTile(Tile):
    def __init__(self, x, y, colony):
        super().__init__('TILE_OCEAN', x, y, colony, 'water')

class DeepOceanTile(Tile):
    def __init__(self, x, y, colony):
        super().__init__('TILE_DEEP_OCEAN', x, y, colony, 'deep_water')